### ISSUE TITLE
Lack of sections

### ISSUE THREAD

**Issue by konhi** [kmaasrud/awesome-obsidian#31]
These and other sections could be added to awesome-obsidian.
- [x] community (e.g. discord, forum, reddit) (see #32)
- [x] resources (e.g. ObsidianRoundup) (see #37)
- [x] about (e.g. articles about obsidian) (see #35)
- [x] [contribute](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)
- [x] for developers (see #36)
- [x] plugins (see #39)
- [x] templates (see #39)
- [x] external tools (see #39)
